db/migrate/20200525141511_add_name_to_users.rb
db/migrate/20200525141559_add_interests_to_users.rb
db/migrate/20200525142043_add_address_to_users.rb
db/migrate/20200525142208_add_bio_to_users.rb
db/migrate/20200525142253_add_age_to_users.rb
db/schema.rb

Migrations for users added to schema.rb

migrations users done

---

db/seeds.rb

users added to seed started the trip generator

---

app/models/trip.rb
app/models/user.rb
db/migrate/20200525144232_create_trips.rb
db/migrate/20200525144549_add_name_to_trips.rb
db/migrate/20200525145202_remove_duration_from_trips.rb
db/schema.rb
test/models/trip_test.rb

trip model done

---

app/models/trip.rb
app/models/trip_venue.rb
app/models/venue.rb
db/migrate/20200525150913_create_venues.rb
db/migrate/20200525151528_create_trip_venues.rb
db/migrate/20200525155704_create_trip_venues.rb
db/schema.rb
test/models/trip_venue_test.rb
test/models/venue_test.rb

Create venue model

---

app/controllers/venues_controller.rb

Need a little check when  trips show will be created

venues controller added and full

---

app/javascript/plugins/init_autocomplete.js
db/schema.rb
package.json
yarn.lock

plugins folder added in javascript
autocompete added need to be tested w/ the last version of the form from the homepage

autocompletion and files added

---

Gemfile
config/environments/development.rb
config/storage.yml
db/schema.rb
db/seeds.rb

setup active storage

---

app/controllers/pages_controller.rb

profile ugly but working

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/config/_general_layout.scss
app/views/layouts/application.html.erb

Front setup (Colors, Fonts, General Layout)

Front setup

---

app/assets/stylesheets/application.scss
app/controllers/trips_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_mapbox.js
app/views/layouts/application.html.erb
app/views/trips/show.html.erb
package.json
yarn.lock

Map is working on trips show 
javascript added 
Should also work on index

Installing map

---

app/views/trips/show.html.erb

old version transformed from dose to venue

---

app/views/devise/registrations/new.html.erb

bootstrap added
name and age added to

form modified

---

app/views/trips/show.html.erb

show page's working just need to add markers to venue on the map

show is now updated with divs list and venues

---

app/views/devise/registrations/new.html.erb

asking picture done

---

app/views/devise/registrations/edit.html.erb

edit user page is modified now you can add all fields of table user

---

app/models/user.rb
app/models/venue.rb

Just need to do the netlinking

active storage added to models user and venue

---

app/assets/stylesheets/components/_map.scss
app/controllers/trips_controller.rb
app/javascript/plugins/init_mapbox.js
app/views/trips/_info_window.html.erb
app/views/trips/show.html.erb

Do not modified the initmapbox

Addind markers for venues in show trip

---

app/views/shared/_navbar.html.erb

netlinking almost don except the activ storage on on the avatar. to fix later today

links added to navbar logo buddies and profile

---

app/views/shared/_footer.html.erb

edited path link on the buddies link in the footer

edited netlinks on the footer

---

app/views/shared/_footer.html.erb
app/views/trips/custom.html.erb

linked the save button the "custom page" to the "trip show" page

linked save button the custom page to the trip show page

---

app/controllers/reviews_controller.rb
app/models/review.rb
app/views/reviews/new.html.erb
db/migrate/20200528105922_create_reviews.rb
db/schema.rb
db/seeds.rb
test/controllers/reviews_controller_test.rb
test/models/review_test.rb

Reviews done just right, need to check the view

Reviews creating

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_navbar.scss
app/controllers/application_controller.rb
app/views/pages/home.html.erb
app/views/pages/profile.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb

managed to link all missing links and fix the navbar

linked all missing  path and fix the navbar

---

app/controllers/application_controller.rb
app/views/shared/_navbar.html.erb

fixed button on the navbar and scroll  to profile

fixed navbar

---

public/404.html
public/422.html
public/500.html

changed error pages 400 404 and 500

created error pages

---

app/controllers/venues_controller.rb
app/models/venue.rb
app/views/reviews/show.html.erb
app/views/venues/index.html.erb
app/views/venues/show.html.erb
config/routes.rb

Venues and reviews

---

app/assets/stylesheets/components/_footer.scss
app/javascript/packs/application.js
app/javascript/plugins/init_autocomplete.js
app/views/pages/profile.html.erb
config/initializers/geocoder.rb

Added autocomplete on the map search and protected JS + mapbox

fixed autocomplete on the map search bar

---

app/controllers/reviews_controller.rb
app/controllers/venues_controller.rb
app/views/layouts/application.html.erb
app/views/venues/index.html.erb
app/views/venues/new.html.erb
app/views/venues/show.html.erb
config/routes.rb

Style for reviews

---

public/404.html
public/422.html
public/500.html

added redirection to HP on the error pages 404, 422 & 500
changed text on buttons on the error pages 404, 422 & 500
edited copy on the error pages 404, 422 & 500

fixed redirection to HP and edited tagline on error pages

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/config/_colors.scss

changed the color and foot sizs

modified footer color

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_general_layout.scss
app/views/pages/profile.html.erb

set up profile page before the prez

profile page setup

---

app/views/trips/_venues_list.html.erb
app/views/trips/custom.html.erb

Removed the 2 search bars on the custom page

removed search bars on custom page

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/config/_colors.scss
app/views/trips/_venues_list.html.erb

modified buttons add and remove on cards

modified buttons ont custom page

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/pages/_custom.scss
app/views/trips/custom.html.erb
db/seeds.rb

styled pictos, added labels and fixed sidebar

styled pictos and added labels and fixed sidebar

---

app/assets/stylesheets/components/_buttons.scss

changed button style

---

app/assets/stylesheets/components/_map.scss
app/javascript/plugins/init_mapbox.js

chose colors depending on captor status

changed map captors

---

app/assets/stylesheets/components/_carousel.scss
app/assets/stylesheets/components/_index.scss
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/venues/show.html.erb

Show venue front

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_sliders.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

css on HP validate generate trip

fixed and styled validate button on HP

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/pages/_custom.scss
app/controllers/trips_controller.rb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb
app/views/trips/_venues_list.html.erb

added aos library
styled venue cards 
changed the scrolling on cards

style venue card and installed aos

---

app/controllers/trips_controller.rb
app/javascript/plugins/init_mapbox.js
app/javascript/plugins/init_mapbox_show.js

modif pictos on maps : show and custom pages

modif pictos on show and custom pages

---

app/views/venues/show.html.erb
db/seeds.rb

seeds pictures

---

app/assets/stylesheets/components/_navbar.scss
app/views/pages/profile.html.erb

modif logo on profile
Custom page : fixed hover on home sidebar

fixed navbar on custom and profile
